export const Ventajas = [
    { id: 1, titulo: "Campus de Primer Nivel", descripcion: "La UAB fomenta el aprendizaje internacional, ser estudiante de la UAB te garantiza un aprendizaje de lengua extranjera continuo y sin costo adicional durante toda tu carrera universitaria.", imagen: "/imagesVentas/web5.jpg" },
    { id: 2, titulo: "Bloque moderno de aulas", descripcion: "Hace un año inauguramos el nuevo y moderno bloque de aulas, con una capacidad de 2500 estudiantes.", imagen: "/imagesVentas/web4.jpg" },
    { id: 3, titulo: "Calidad Académica", descripcion: "La UAB tiene convenios que permite a los estudiantes hacer intercambios estudiantiles internacionales con otras universidades adventistas en el mundo.", imagen: "/imagesVentas/web14-1.jpg" },
    { id: 4, titulo: "Experiencia integral", descripcion: "La UAB tiene convenios que permite a los estudiantes hacer intercambios estudiantiles internacionales con otras universidades adventistas en el mundo.", imagen: "/imagesVentas/web14.jpg" },
    { id: 5, titulo: "Intercambios estudiantiles", descripcion: "La UAB tiene convenios que permite a los estudiantes hacer intercambios estudiantiles internacionales con otras universidades adventistas en el mundo.", imagen: "/imagesVentas/web14.jpg" },
    { id: 6, titulo: "Biblioteca Virtual", descripcion: "Centro de estudios y aprendizaje para la investigación con mas de 100.000 libros online.", imagen: "/imagesVentas/DSC_1616.jpg" },
    { id: 7, titulo: "Residencias Estudiantiles", descripcion: "Alimentación vegetariana buffet. Escuela de deportes y natación gratuita Modernas piezas.", imagen: "/imagesVentas/DSC_1712.jpg" },
    { id: 8, titulo: "Ingles Gratuito", descripcion: "La UAB fomenta el aprendizaje internacional, ser estudiante de la UAB te garantiza un aprendizaje de lengua extranjera continuo y sin costo adicional durante toda tu carrera universitaria.", imagen: "/imagesVentas/DSC_1588.jpg" },
];