export const Carreras = [
    { id: 1, title: "Ingeniería de Sistemas", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-sistemas-pm8uj2l2r7z39ij308nvv5466koguzpp4usw0gyk7k.jpg" },
    { id: 2, title: "Ingeniería en Redes y Telecomunicaciones", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-telecom-pm8uihwmkv6s63d4czq3cac143ie5nflq0g7gdt80g.jpg" },
    { id: 3, title: "Ingeniería Ambiental", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-amb-pm8uhy60lcfrea5sk96xdxbcn07oo098nar0dkmhn4.jpg" },
    { id: 4, title: "Administración y Negocios Internacionales", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-admi-pm8un1gjm1eoa8rjtyf6e528h549czgwchyoyj2pxs.jpg" },
    { id: 5, title: "Contaduría Pública", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/DSC_1435-pm93ghibpryt9bno669bh18ersgux1pgnpk1ooe8k0.jpg" },
    { id: 6, title: "Ingeniería Comercial", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-com-pm8uo7ra5l0ksp23yype0cdz7hbrzd4tibbjjzc05s.jpg" },
    { id: 7, title: "Psicologia", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-psicologia-pm8unm4zse6zdnxih7cywzudjmac2bqzrcbdim824w.jpg" },
    { id: 8, title: "Psicopedagogia", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-psicopedagogia-pm8ujn9ixkrecxp1nhlodzwb91ujkbzsjp5kkk3weo.jpg" },
    { id: 9, title: "Actividad Fisica y Deportes", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-act-pm8uldavgn4bn76xl8f1yk8qghcrocu2s87m8tjx00.jpg" },
    { id: 10, title: "Enfermeria", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-enfermeria-pm8uksmfaac0js0yxzh9fpgle06oz0jzdduxoqeksw.jpg" },
    { id: 11, title: "Nutricion y Dietetica", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-nutri-pm8ulx1hg5vcf0e9dyy7wx9exknh600fuxwtbmqndc.jpg" },
    { id: 12, title: "Fisioterapia y Kinesiologia", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web-fisio-pm8uk7xz3xjpgcv0aqjgwuogbj0m9o9vyji94n98ls.jpg" },
    { id: 13, title: "Bioquimica", duracion: "Nivel licenciatura - 4 Años - Sín exámen de ingreso.", img: "imagesCarreras/web1-pm8umhpxminnifk817w0fs1k01tjvcaj9s9hvpvzkg.jpg" },
    { id: 14, title: "Teologia", duracion: "Nivel licenciatura - 4 Años - Con exámen de ingreso.", img: "imagesCarreras/web-teo-pm8uhefeltoqmgygrinrfkao5wwz6d2vkl1tarfr9s.jpg" }];