import { materiasAdmi, materiasIngAmbiental, materiasIngRedesT, materiasIngSistemas } from "./materiasCarrera";
import { objAdmi, objIngAmbiental, objIngRedesT, objIngSistemas } from "./objetivosCarrera";

export const infoCarreras = [
    {
        id: 1, head: { title: "Ingeniería de Sistemas", description: "Ingeniería de Sistemas es una rama de la ingeniería que trabaja con un producto de alta complejidad como es el software. En la actualidad, las actividades principales del ser humano funcionan de forma más eficiente con un software. Nada es óptimo sin un software. Por ese motivo, la Ingeniería de Sistemas es una de las carreras con más demanda en el mercado mundial.", cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" } }, body: { perfil_campo: { perfil: "Los Ingenieros de Sistemas son expertos en el diseño, construcción, instalación, testeo, mantenimiento y gerenciamiento del software. El Ingeniero de Sistemas es referente en temas de tecnología para la construcción de soluciones a problemas de gran escala aplicando los conocimientos de la ingeniería e informática. Actualmente, el estado de esta ingeniería está altamente especializado. Es por eso que esta profesión permite dedicarse a diferentes áreas específicas. Por ejemplo: desarrollador de Apps, desarrollador de juegos, Arquitecto de TI, Gerente de TI, Científico de Datos, Project Manager, Hacker ético, Consultor de TI, emprendedor y muchos más.", campo: "Un Ingeniero de Sistemas puede trabajar prácticamente en cualquier empresa. Toda institución necesita profesionales que lideren los procesos de transformación digital, planteen soluciones estratégicas acordes a las necesidades del mercado actual y se adapten a los avances tecnológicos. Los requerimientos de profesionales en Ingeniería de Sistemas se han incrementado de manera exponencial en Bolivia y en el mundo. Y, gracias a la tecnología, nuestros profesionales pueden trabajar desde Bolivia para el mundo." }, plan_de_estudios: materiasIngSistemas, footer: { desc: "El mundo en que vivimos está transformado por las obras de la ingeniería. Crear, innovar y transformar forma parte de la esencia de un ingeniero. Un(a) ingeniero(a) ayuda a resolver problemas que son importantes para la sociedad. De ahí su prestigio. Si te gusta lo diferente y lo innovador ¡esta es la profesión para ti!. Las alternativas laborales son abundantes y variadas. Pocas profesiones te dan una verdadera oportunidad de trabajar por un mundo mejor. ¡Ser ingeniero(a) es genial!", objetivos: objIngSistemas } }
    },


    {
        id: 2, head: {
            title: "Ingeniería en Redes y Telecomunicaciones", description: "La carrera de Ingeniería en Redes y Telecomunicaciones forma profesionales para liderar el manejo de la tecnología. Profesionales competentes, innovadores, capaces de gestionar soluciones integrales que promuevan el desarrollo de la ciencia y tecnología. El plan de estudio está diseñado para conseguir que el futuro graduado se desempeñe en las empresas de telecomunicaciones en el área de telemática y redes de datos.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "La carrera de Ingeniería en Redes y Telecomunicaciones de la Universidad Adventista de Bolivia tiene el fin de formar profesionales competentes con una sólida formación tecnológica y un conjunto de habilidades técnicas con aprecio a los principios de la ética cristiana. Durante el programa académico adquiere conocimientos necesarios para el diseño de redes y sistemas integrados de telecomunicaciones, telemática, comprometidos con la formación de valores inculcados en la universidad.A su vez está dispuesto a liderar y colaborar en proyectos en equipos de trabajo de forma innovadora y eficiente, comunicando ideas y conceptos propios de su profesión en entornos dinámicos. Gestiona eficientemente los recursos a su disposición y propone soluciones que promuevan un desarrollo sostenible en la organización, Participa en el desarrollo de planes de implementación tecnológica y de ingeniería aplicada considerando los costos y beneficios asociados al diseño, mantención, evaluación y control de los sistemas electrónicos y de telecomunicaciones.", campo: "La ingeniería en Redes y Telecomunicaciones es una rama de la ingeniería que resuelve problemas de transmisión y recepción de señales e interconexión de redes. Es la disciplina de aplicación de la telecomunicación, término que se refiere a la comunicación a distancia, generalmente a través de la propagación de ondas electromagnéticas y ópticas. Esto incluye muchas tecnologías, como radio, televisión, teléfono, comunicaciones de datos y redes informáticas como Internet. El Ingeniero en Redes y Telecomunicaciones es responsable del diseño, instalación y configuración de equipos de redes y telecomunicaciones. Son expertos en el envío y recepción de datos sobre diferentes medios de comunicación. Además, es experto en redes informáticas. Algunas de las más utilizadas hoy en día son: LAN, MAN, WAN requerimientos de profesionales en Ingeniería de Sistemas se han incrementado de manera exponencial en Bolivia y en el mundo. Y, gracias a la tecnología, nuestros profesionales pueden trabajar desde Bolivia para el mundo." },
            plan_de_estudios: materiasIngRedesT, footer: { desc: "La carrera en Redes y Telecomunicaciones de la UAB busca promover el desarrollo integral de los estudiantes, en los aspectos físicos, mentales, sociales y espirituales. El ingeniero en Redes y Telecomunicaciones tendrá experiencia en investigación e innovación, competente y éticamente responsable, al servicio de Dios y la Humanidad, en pos del crecimiento tecnológico y en coherencia con una cosmovisión bíblica-cristiana que es el fundamento de su quehacer profesional y social. Además, es una carrera que pretende posicionarse en el manejo de la tecnología en el campo de las telecomunicaciones y redes de computadoras mediante un plan de estudios flexibles permitiendo a los estudiantes una integración con otros programas de especialidad favoreciendo la posibilidad de doble programa.", objetivos: objIngRedesT }
        }
    },


    {
        id: 3, head: {
            title: "Ingeniería Ambiental", description: "La carrera de Ingeniería Ambiental es un proyecto educativo que tiene el objetivo de la formar profesionales de manera integral, es decir que tengan los conocimientos profundos en la disciplina, que le permita insertarse en el mercado laboral y también, que contribuya a su contexto social de manera crítica y constructiva.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El Ingeniero Ambiental formado en la Universidad Adventista de Bolivia, es un profesional con una visión integral, capaz de identificas y proponer alternativas de solución a problemas medioambientales, aplicando conocimientos científicos, tecnológicos y humanísticos; optimizando procesos y minimizando costos, que permite el desarrollo sostenible y sustentable de la industria, previniendo problemas de contaminación o minimizando el impacto a través de estrategias de reutilización e incorporación de nuevas tecnologías de procesamiento y de control.", campo: "Los ámbitos de realización del profesional del Ingeniero Ambiental egresado de la Universidad Adventista de Bolivia son: • Seguridad Industrial: En la diversidad de industrias, aplica los conocimientos de Seguridad y Salud Ocupacional, para definir medidas de control y prevenir accidentes laborales, aplicando la Legislación y Normas vigentes tanto nacionales como internacionales, con el objetivo de anticipar, reconocer, evaluar y controlar los riesgos que puedan afectar la seguridad y la salud en el trabajo. • Monitoreo y Saneamiento Ambiental: El profesional realiza la gestión de supervisión y control en la implementación de proyectos industriales, evaluación y seguimiento de procesos industriales dirigidas a evitar, mitigar o revertir impactos negativos en el ambiente producto de las actividades humanas. • Investigación: En las organizaciones, genera nuevos conocimientos en la disciplina, enfocados en la prevención y el uso sostenible de los recursos del medio ambiente." },
            plan_de_estudios: materiasIngAmbiental, footer: { desc: "La carrera de Ingeniería Ambiental y Seguridad Industrial, te ofrece la oportunidad de formarte como profesional y ser un actor importante en la preservación del medio ambiente. Por eso el desarrollo y el futuro de la humanidad está relacionado con la labor trascendente del ingeniero ambiental. Esta es tu oportunidad para puedas formarte como profesional y contribuir para mejorar la calidad de vida de nuestra sociedad.", objetivos: objIngAmbiental }
        }
    },


    {
        id: 4, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },

//
    {
        id: 5, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 6, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 7, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 8, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 9, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 10, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 11, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 12, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 13, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 14, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },

];