import { materiasAdmi, materiasIngAmbiental, materiasIngRedesT, materiasIngSistemas, materiasContaduria, materiasIngComercial, materiasPsicologia, materiasPsicopedagogia, materiasEducacionFisica, materiasEnfermeria, materiasNutricion, materiasFisioterapia, materiasBioquimica, materiasTeologia } from "./materiasCarrera";
import { objAdmi, objBioquimica, objContaduria, objEducacionFisica, objEnfermeria, objFisioterapia, objIngAmbiental, objIngComercial, objIngRedesT, objIngSistemas, objNutricion, objPsicologia, objPsicopedagogia, objTeologia } from "./objetivosCarrera";

export const infoCarreras = [
    {
        id: 1, head: { title: "Ingeniería de Sistemas", description: "Ingeniería de Sistemas es una rama de la ingeniería que trabaja con un producto de alta complejidad como es el software. En la actualidad, las actividades principales del ser humano funcionan de forma más eficiente con un software. Nada es óptimo sin un software. Por ese motivo, la Ingeniería de Sistemas es una de las carreras con más demanda en el mercado mundial.", cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" } }, body: { perfil_campo: { perfil: "Los Ingenieros de Sistemas son expertos en el diseño, construcción, instalación, testeo, mantenimiento y gerenciamiento del software. El Ingeniero de Sistemas es referente en temas de tecnología para la construcción de soluciones a problemas de gran escala aplicando los conocimientos de la ingeniería e informática. Actualmente, el estado de esta ingeniería está altamente especializado. Es por eso que esta profesión permite dedicarse a diferentes áreas específicas. Por ejemplo: desarrollador de Apps, desarrollador de juegos, Arquitecto de TI, Gerente de TI, Científico de Datos, Project Manager, Hacker ético, Consultor de TI, emprendedor y muchos más.", campo: "Un Ingeniero de Sistemas puede trabajar prácticamente en cualquier empresa. Toda institución necesita profesionales que lideren los procesos de transformación digital, planteen soluciones estratégicas acordes a las necesidades del mercado actual y se adapten a los avances tecnológicos. Los requerimientos de profesionales en Ingeniería de Sistemas se han incrementado de manera exponencial en Bolivia y en el mundo. Y, gracias a la tecnología, nuestros profesionales pueden trabajar desde Bolivia para el mundo." }, plan_de_estudios: materiasIngSistemas, footer: { desc: "El mundo en que vivimos está transformado por las obras de la ingeniería. Crear, innovar y transformar forma parte de la esencia de un ingeniero. Un(a) ingeniero(a) ayuda a resolver problemas que son importantes para la sociedad. De ahí su prestigio. Si te gusta lo diferente y lo innovador ¡esta es la profesión para ti!. Las alternativas laborales son abundantes y variadas. Pocas profesiones te dan una verdadera oportunidad de trabajar por un mundo mejor. ¡Ser ingeniero(a) es genial!", objetivos: objIngSistemas } }
    },
    {
        id: 2, head: {
            title: "Ingeniería en Redes y Telecomunicaciones", description: "La carrera de Ingeniería en Redes y Telecomunicaciones forma profesionales para liderar el manejo de la tecnología. Profesionales competentes, innovadores, capaces de gestionar soluciones integrales que promuevan el desarrollo de la ciencia y tecnología. El plan de estudio está diseñado para conseguir que el futuro graduado se desempeñe en las empresas de telecomunicaciones en el área de telemática y redes de datos.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "La carrera de Ingeniería en Redes y Telecomunicaciones de la Universidad Adventista de Bolivia tiene el fin de formar profesionales competentes con una sólida formación tecnológica y un conjunto de habilidades técnicas con aprecio a los principios de la ética cristiana. Durante el programa académico adquiere conocimientos necesarios para el diseño de redes y sistemas integrados de telecomunicaciones, telemática, comprometidos con la formación de valores inculcados en la universidad.A su vez está dispuesto a liderar y colaborar en proyectos en equipos de trabajo de forma innovadora y eficiente, comunicando ideas y conceptos propios de su profesión en entornos dinámicos. Gestiona eficientemente los recursos a su disposición y propone soluciones que promuevan un desarrollo sostenible en la organización, Participa en el desarrollo de planes de implementación tecnológica y de ingeniería aplicada considerando los costos y beneficios asociados al diseño, mantención, evaluación y control de los sistemas electrónicos y de telecomunicaciones.", campo: "La ingeniería en Redes y Telecomunicaciones es una rama de la ingeniería que resuelve problemas de transmisión y recepción de señales e interconexión de redes. Es la disciplina de aplicación de la telecomunicación, término que se refiere a la comunicación a distancia, generalmente a través de la propagación de ondas electromagnéticas y ópticas. Esto incluye muchas tecnologías, como radio, televisión, teléfono, comunicaciones de datos y redes informáticas como Internet. El Ingeniero en Redes y Telecomunicaciones es responsable del diseño, instalación y configuración de equipos de redes y telecomunicaciones. Son expertos en el envío y recepción de datos sobre diferentes medios de comunicación. Además, es experto en redes informáticas. Algunas de las más utilizadas hoy en día son: LAN, MAN, WAN requerimientos de profesionales en Ingeniería de Sistemas se han incrementado de manera exponencial en Bolivia y en el mundo. Y, gracias a la tecnología, nuestros profesionales pueden trabajar desde Bolivia para el mundo." },
            plan_de_estudios: materiasIngRedesT, footer: { desc: "La carrera en Redes y Telecomunicaciones de la UAB busca promover el desarrollo integral de los estudiantes, en los aspectos físicos, mentales, sociales y espirituales. El ingeniero en Redes y Telecomunicaciones tendrá experiencia en investigación e innovación, competente y éticamente responsable, al servicio de Dios y la Humanidad, en pos del crecimiento tecnológico y en coherencia con una cosmovisión bíblica-cristiana que es el fundamento de su quehacer profesional y social. Además, es una carrera que pretende posicionarse en el manejo de la tecnología en el campo de las telecomunicaciones y redes de computadoras mediante un plan de estudios flexibles permitiendo a los estudiantes una integración con otros programas de especialidad favoreciendo la posibilidad de doble programa.", objetivos: objIngRedesT }
        }
    },
    {
        id: 3, head: {
            title: "Ingeniería Ambiental", description: "La carrera de Ingeniería Ambiental es un proyecto educativo que tiene el objetivo de la formar profesionales de manera integral, es decir que tengan los conocimientos profundos en la disciplina, que le permita insertarse en el mercado laboral y también, que contribuya a su contexto social de manera crítica y constructiva.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El Ingeniero Ambiental formado en la Universidad Adventista de Bolivia, es un profesional con una visión integral, capaz de identificas y proponer alternativas de solución a problemas medioambientales, aplicando conocimientos científicos, tecnológicos y humanísticos; optimizando procesos y minimizando costos, que permite el desarrollo sostenible y sustentable de la industria, previniendo problemas de contaminación o minimizando el impacto a través de estrategias de reutilización e incorporación de nuevas tecnologías de procesamiento y de control.", campo: "Los ámbitos de realización del profesional del Ingeniero Ambiental egresado de la Universidad Adventista de Bolivia son: • Seguridad Industrial: En la diversidad de industrias, aplica los conocimientos de Seguridad y Salud Ocupacional, para definir medidas de control y prevenir accidentes laborales, aplicando la Legislación y Normas vigentes tanto nacionales como internacionales, con el objetivo de anticipar, reconocer, evaluar y controlar los riesgos que puedan afectar la seguridad y la salud en el trabajo. • Monitoreo y Saneamiento Ambiental: El profesional realiza la gestión de supervisión y control en la implementación de proyectos industriales, evaluación y seguimiento de procesos industriales dirigidas a evitar, mitigar o revertir impactos negativos en el ambiente producto de las actividades humanas. • Investigación: En las organizaciones, genera nuevos conocimientos en la disciplina, enfocados en la prevención y el uso sostenible de los recursos del medio ambiente." },
            plan_de_estudios: materiasIngAmbiental, footer: { desc: "La carrera de Ingeniería Ambiental y Seguridad Industrial, te ofrece la oportunidad de formarte como profesional y ser un actor importante en la preservación del medio ambiente. Por eso el desarrollo y el futuro de la humanidad está relacionado con la labor trascendente del ingeniero ambiental. Esta es tu oportunidad para puedas formarte como profesional y contribuir para mejorar la calidad de vida de nuestra sociedad.", objetivos: objIngAmbiental }
        }
    },
    {
        id: 4, head: {
            title: "Administración y Negocios Internacionales", description: "La carrera de Administración y Negocios Internacionales forma emprendedores que responden a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio. Los estudiantes de la carrera tienen la oportunidad de realizar sus prácticas profesionales en más de 23 empresas con convenio además de la Aduana Nacional. Al pertenecer a la red mundial de universidades adventistas los estudiantes tienen la opción de estudiar un semestre en universidades de Sudamérica.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional de Administración y Negocios Internacionales es un emprendedor que responde a un alto código de ética profesional aplicando principios de responsabilidad, lealtad, respeto y espíritu de servicio cuyas competencias le permiten: Ejecutar, mejorar e innovar los procesos administrativos. Diseñar, formular, ejecutar, controlar y evaluar estrategias de gestión empresarial que involucren planes estratégicos y operativos.       Liderar, dirigir y desarrollar equipos interdisciplinarios de trabajo.Interpretar la información contable y la información financiera para la toma de decisiones gerenciales.", campo: "El Profesional en Administración y Negocios Internacionales tiene un amplio campo laboral, puede desempeñarse en cualquier tipo de empresa, comercial, industrial, de servicios, pública o sin fines de lucro, asumiendo funciones y una carrera profesional en las áreas de marketing, producción, finanzas, recursos humanos y en todos los niveles administrativos. Está preparado para gestionar negocios internacionales, como logística de importación y exportación, así mismo tiene la capacidad de emprender su propio negocio y convertirlo en una empresa." },
            plan_de_estudios: materiasAdmi, footer: { desc: "La administración es fundamental en la vida del ser humano, todos administramos algo, desde el tiempo, nuestro cuerpo, los recursos que tenemos, siempre con el objetivo de mejorar nuestra situación personal o familiar. Así mismo, nuestro estilo de vida está altamente influenciado por un sinfín de productos y servicios que fueron pensados, y desarrollados por alguna organización, y esa organización liderada por un administrador. Actualmente estamos atravesando una crisis sanitaria a nivel mundial que ha afectado en muchos aspectos nuestro estilo de vida y nuestra situación familiar, económica y social. En este tiempo sin precedentes nuestra sociedad y nuestro país necesita jóvenes dispuestos a hacer lo correcto sin importar las consecuencias, jóvenes que quieran usar sus capacidades y creatividad para solucionar problemas y fomentar el desarrollo del país a través de emprendimientos lícitos y responsables con nuestro planeta, jóvenes que además de poseer las competencias profesionales puedan adaptarse a nuestro entorno en constante cambio, jóvenes que puedan y estén dispuestos a liderar una transformación mundial desde su influencia local. Tu puedes ser parte de ese ejército de líderes que el mundo necesita, ¡te esperamos!", objetivos: objAdmi }
        }
    },
    {
        id: 5, head: {
            title: "Contaduría Pública", description: "La Carrera de Contaduría Pública es una profesión del área financiera empresarial que tiene como propósito registrar y analizar el proceso económico y/o financiero de un ente, ya sea del sector público o privado. Al estudiar esta carrera podrás asesorar a pequeñas y grandes empresas en temas financieros para que éstas puedan tomar decisiones acertadas y concretas que les permita avanzar en el logro de sus objetivos. Al formarte como contador público estarás provisto de conocimientos y habilidades contables, financieras, de auditoría, tributos y empresariales que te permitirán asesorar a personas, empresas y grandes organizaciones con relación al cumplimiento de las normas contables, de auditoría, legales y fiscales del país.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "Altamente competente y líder por excelencia, con sólidos conocimientos en las ciencias empresariales. • Experto en el desarrollo e implementación de estrategias, instrumentos y procesos que dan solución óptima a los problemas económicos y financieros. • Hábil en preparar, analizar y diseñar sistemas para la emisión de estados financieros, con el uso de tecnologías informáticas y aplicación de normativas. • Independiente e íntegro, que planifica, ejecuta el trabajo de auditoría tanto interna como externa y que emite dictámenes con carácter público o privado. • Especialista en la consultoría tributaria, gestión y procesos administrativos, control interno, mercados financieros, sistemas de costeo, presupuestos y otros. • Formado con principios y valores cristianos, su integridad da una certera confianza en su entorno y la sociedad.", campo: "El campo laboral de la carrera de Contaduría Pública, engloba el desarrollo profesional en entidades públicas y privadas en cargos operativos, gerenciales y académicos, relacionados con las áreas de Contabilidad, Auditoría, finanzas, tributación y administración, así como en entidades sin fines de lucro a cargo de la proyección, ejecución y elaboración de productos financieros como también de proyectos de desarrollo." },
            plan_de_estudios: materiasContaduria, footer: { desc: "La formación de los futuros profesionales en Contaduría Pública es una responsabilidad con Dios y la sociedad. “Los lineamientos que otorgan el sentido de nuestra actividad educativa está dirigida al desarrollo de una efectiva calidad de vida para las personas, especialmente para nuestros estudiantes, el vínculo con el entorno, el fomento de las nuevas actividades empresariales, en una permanente innovación y adaptación tecnológica de sus actividades, orientadas a las necesidades institucionales cada vez más exigentes en un mundo carente de principios y valores”.", objetivos: objContaduria }
        }
    },
    {



        id: 6, head: {
            title: "Ingeniería Comercial", description: "La Carrera de Ingeniería Comercial aplica conocimientos de estadística, métodos cuantitativos, investigación de mercado, economía, administración, finanzas y marketing para la solución de los problemas sociales y organizacionales; como enfoque principal la gerencia empresarial. En ella se combinan la administración con la economía, estudiando las relaciones comerciales de la empresa a nivel nacional e internacional. Está dirigida al desarrollo y ejecución de soluciones de negocios y es parte en la toma de decisiones productivas y organizativas a nivel de gerencia.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: "Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El Ingeniero Comercial es un profesional creativo, innovador, con sólidos conocimientos en marketing y habilidades en el manejo de herramientas técnicas, tecnológicas para la toma de decisiones estratégicas el ámbito comercial que le permiten contar con habilidades y capacidades para: Investigar mercados, a través del comportamiento del consumidor. Elaborar planes estratégicos de marketing, así como la implementación y gestión. Detectar oportunidades para emprender nuevos negocios y/o desarrollar nuevos productos. Planificar, ejecutar, asesorar, evaluar y controlar los procesos de gestión comercial, en organizaciones empresariales. Diseñar y ejecutar campañas de marketing digital, creación de contenido para el posicionamiento digital de las organizaciones.", campo: "Un Ingeniero Comercial puede desempeñarse en altos cargos gerenciales dentro de una organización, es un profesional íntegro , innovador y preparado para asumir los retos del mercado laboral; puede asumir cargos de Gerente General, Gerente de Ventas, Gerente de Marketing, Consultor de Empresas, Gerente de Proyectos Nacionales, Gerente de Producción, Gerente de Finanzas, Gestión Estratégica de Negocios, Asesor Multidisciplinario de Actividades económicas y comerciales, Director de Investigación de Mercados y Desarrollo de Nuevos Productos, Experto en Crear Imagen Institucional, Experto en Marketing digital y Community Manager." },
            plan_de_estudios: materiasIngComercial, footer: { desc: "La carrera de ingeniería comercial, comprometida con la comunidad boliviana responde al cambio de la sociedad mundial, implementando nuevas estrategias y metodologías educativas que juntamente al uso de medios tecnológicos permiten la formación de profesionales competentes, íntegros e innovadores. En nuestra carrera transformamos el esfuerzo en éxito, en el marco de una nueva dinámica de gestión académica y administrativa trabajamos coordinadamente con un equipo humano altamente cualificado y comprometido con el futuro profesional de cada uno de nuestros estudiantes, hemos desarrollado e implementado estrategias para una experiencia académica vivencial única, te invito a recorrer juntos este camino de aprendizaje, estudio y servicio.", objetivos: objIngComercial }
        }
    },
    {
        id: 7, head: {
            title: "Psicología", description: "La Psicología es la profesión en la que se detectan, evalúan y proponen estrategias de prevención y solución a patologías de orden psicológico, mismas que son procedentes de la interacción entre individuos, grupos, instituciones y comunidades para el desarrollo del ser humano y la sociedad.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El psicólogo de la UAB, es un profesional que promueve la salud mental y el mejoramiento de la calidad de vida en el ser humano, tiene la capacidad de lidiar con las dificultades emergentes de su práctica profesional con una mirada de búsqueda del bienestar psicosocial, diagnosticando y acompañando a resolver los problemas de orden psicológico, así como prevenirlos, sosteniendo sus valores ético cristianos y utilizando la investigación científica, como la herramienta principal que le permite afrontar situaciones procedentes del cambio coyuntural de la sociedad.", campo: "Puede desempeñarse en área de la educación, la salud, la producción y grupos específicos. • Educación, trabaja en guarderías, centros de educación especial, terapia educativa, comunidades de investigación educativa. • Salud, trabaja en hospitales, clínicas, centros de rehabilitación especializada y consultorios particulares. • Producción, trabaja en organizaciones dentro de recursos humanos, programas de reclutamiento, selección de personal, clima laboral e investigación de variables que influyen en la conducta del consumidor.• Grupos específicos, trabaja en programas de acción social, investigación comunitaria y atención a poblaciones rurales, e indígenas desde una mirada de la psicología social." },
            plan_de_estudios: materiasPsicologia, footer: { desc: "La psicología, es una ciencia de alta responsabilidad social, pensamiento crítico y sólida formación integral al servicio de la sociedad y en la UAB, asumimos esta labor con el más alto espíritu de reflexión y compromiso para cubrir eficazmente, todas las expectativas emergentes de una sociedad en constante cambio. Te invito a sumarte a un equipo con competencias comunicativas, de planeación y desarrollo profesional constante.", objetivos: objPsicologia }
        }
    },
    {
        id: 8, head: {
            title: "Psicopedagogía", description: "La Carrera de Psicopedagogía proporciona herramientas de formación teórica y práctica que comprende el estudio de los procesos cognitivos que intervienen en el aprendizaje y todas las formas de enseñanza. Toma en cuenta y analiza diversas perspectivas metodológicas referidas al aprendizaje, todo ello en función del diseño e implementación de estrategias psicopedagógicas que permitan dar respuestas adecuadas a las condiciones y características de cada persona, en un contexto determinado y con los instrumentos necesarios para optimizar el aprendizaje.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El Psicopedagogo será capaz de: • Desarrollar competencias y capacidades para la intervención psicopedagógica a nivel individual, dentro del marco de la acción clínico psicopedagógica. • Promover la orientación psicopedagógica, conforme al marco de la asesoría y la organización pedagógica, de acuerdo a la normativa educativa vigente. • Detectar y diagnosticar las dificultades del aprendizaje, a partir de métodos y técnicas formales e informales, dentro del marco del método clínico aplicado a la educación. • Diseñar programas profilácticos en psicopedagogía, a partir de las características y necesidades de cada población. • Promover estrategias de prevención psicopedagógica, mediante programas psico educacionales dirigidos a poblaciones en su diversidad. • Propiciar estrategias metodológicas de la psicopedagogía, para la intervención reeducativa a nivel grupal dentro de las instituciones educativas y dentro de los grupos sociales constituidos de manera transitoria o permanente. • Actuar dentro de los principios ético y deontológicos necesario para el correcto ejercicio profesional en cada uno de los ámbitos de la actuación profesional. • Aplicar procesos metodológicos de investigación enfocados a la solución de problemas de la sociedad en el ámbito psicoeducativo.", campo: "Los campos de actuación u campo ocupacional del profesional en Psicopedagogía son: • Establecimiento educacional en los niveles preescolares, primario, secundario y terciario. Hogares de menores Centros Hospitalarios Escuelas de educación especial Centros de diagnósticos Centros de orientación familiar, laboral y comunitaria Clínicas psicopedagógicas Institutos psicopedagógicos especializados." },
            plan_de_estudios: materiasPsicopedagogia, footer: { desc: "El profesional en Psicopedagogía es un estratega que trabaja sobre el aprendizaje. Promueve y acompaña espacios educativos inclusivos y significativos, respetando cada una de las etapas del desarrollo por las cuales atraviesa el ser humano, logrando vincularse profesionalmente con niños, adolescentes, jóvenes, adultos y adultos mayores, respetando su individualidad y sus características personales.", objetivos: objPsicopedagogia }
        }
    },
    {
        id: 9, head: {
            title: "Actividad Física y Deportes", description: "La carrera de Actividad Física y Deportes de la UAB tiene como objetivo preparar profesionales para el desarrollo de la educación física, el deporte y la recreación para las distintas unidades educativas, escuelas deportivas departamentales e instituciones privadas. Para ello contamos con el mejor campus deportivo del país con canchas deportivas reglamentarias de fútbol, voleibol, básquetbol y futsal. Además de una pista atlética y una piscina semiolímpica temperada.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: "Ingreso con examen" }
        }, body: {
            perfil_campo: { perfil: "El graduado de la Maestría en Educación, estará capacitado para: Dirigir diversos tipos de organizaciones en diferentes contextos, haciendo uso de sus capacidades de comunicación efectiva, liderazgo y trabajo en equipos de alto desempeño Diseñar, planificar e intervenir utilizando herramientas metodológicas de la gestión administrativa que inciden en el ámbito empresarial y fomentan el emprendimiento organizacional. Aplicar sus conocimientos y destrezas para enfrentar los cambios del entorno económico y comercial, impulsando el desarrollo empresarial. Diseñar estrategias innovadoras de marketing para organizaciones que conduzcan al logro de sus objetivos. Utilizar de forma eficiente sus habilidades para planificar, organizar, controlar, integrar, supervisar y evaluar las acciones de mejoramiento empresarial. Enfrentar los cambios que se presentan en los mercados nacionales e internacionales y responde de modo óptimo a las diferentes exigencias del entorno económico, político, social y tecnológico que enfrentan las empresas. Liderar una organización empresarial en beneficio del mejoramiento socio económico del país, con responsabilidad social y en armonía con el medio ambiente. Utilizar metodologías de investigación científica con miras a optimizar el desarrollo y el éxito de una empresa.", campo: "El licenciado en Ciencias de la Actividad Física y deportes podrá trabajar como, entrenador personal, preparador Físico, entrenador en escuelas deportivas, profesor de educación física y deportes (colegios privados), personas con discapacidad, personas de la tercera edad, de la misma forma en para parte de administración y gestión en centros deportivos, alcaldías." },
            plan_de_estudios: materiasEducacionFisica, footer: { desc: "La carrera de Ciencias de la Actividad Física y Deportes abre las puertas para todos los estudiantes de Sud América, para aprender y capacitarse en la planificación, implementación, enseñanza y administración de la actividad física y el deporte en sus diferentes niveles. Durante 8 semestres de estudio, con docentes altamente capacitados, contando con una de las mejores infraestructuras deportivas a nivel nacional, acorde para la enseñanza de nuestros futuros profesionales al servicio de la sociedad.", objetivos: objEducacionFisica }
        }
    },
    {
        id: 10, head: {
            title: "Enfermería", description: "La Carrera de Enfermería con 30 años de trayectoria, es una profesión que ha sabido responder a las necesidades de la población. La carrera forma profesionales con una preparación científica además de responsabilidad social y valores éticos cristianos, ejerciendo el liderazgo para brindar un cuidado holístico a las personas, familia y comunidad, sana o enferma, con miras de mantener o recuperar la salud del ser humano en todo los aspectos biológicos, psicológicos, sociales y espirituales.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años y medio (9 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional Licenciado en enfermería egresado de la Universidad Adventista de Bolivia, estará capacitado para desempeñar funciones en las siguientes áreas: Asistencial Brinda cuidado integral de calidad en los procesos de salud enfermedad de las distintas fases del ciclo vital, a fin de mantener y/o recuperar la salud persona familia y comunidad en los distintos niveles de atención de salud, considerando el aspecto físico, social, psicológico, cultural y espiritual.Administrativa Aplica los elementos de administración y gestión en los servicios de salud de los distintos niveles de atención, bajo los criterios de calidad y gestión de liderazgo. Investigación Desarrolla investigaciones científicas y propone alternativa de solución a los problemas de salud desde la gestión del cuidado enfermero, con compromiso ético y responsabilidad. Docencia Desarrolla actividades de Docencia, en base a estrategias pedagógicas, didácticas y tecnológicas, mostrando responsabilidad y competitividad, en la formación de profesionales y no profesionales en salud.", campo: "Asistencial: El profesional puede trabajar en Hospitales particulares, públicos de primer, segundo y tercer nivel del Ministerio de Salud, empresas, ONGs, fuerzas armadas. Administración: Cargos administrativos en hospitales particulares, públicos, universidades y otras instituciones. Docencia: Universidades formadoras de recursos humanos, institutos superiores, centro de educación permanente de los servicios de salud. Investigaciones científicas, proyectos en salud en ONGs y alcaldías." },
            plan_de_estudios: materiasEnfermeria, footer: { desc: "Te invito estudiar Enfermería con nosotros, una Carrera que te brindará enorme satisfacción profesional y personal, en la que tendrás la oportunidad de crecer en forma integral, sentirte útil y capaz de aportar a la sociedad a través del mejoramiento de la salud y el bienestar de las personas. Realizaras prácticas clínicas y comunitarias desde el primer semestre, desarrollando las competencias, destrezas y habilidades, para brindar un cuidado humanizado al usuario sano o enfermo.", objetivos: objEnfermeria }
        }
    },
    {
        id: 11, head: {
            title: "Nutrición y Dietética", description: "La carrera de Nutrición y Dietética de la Universidad Adventista de Bolivia, centra su formación en un estilo de vida saludable, potenciando en nuestros estudiantes talentos, capacidades y dones de forma integral, velando por un desarrollo armonioso de la parte física, mental y espiritual. Capacitamos a nuestros estudiantes para trabajar en el área clínica, comunitaria, administrativa, investigación y docencia, con sólidos principios y valores cristianos.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "Aplica la evaluación, diagnóstico y tratamiento dietoterápico nutricional con énfasis en el arte del cuidado de la alimentación saludable para conservar la salud de la persona, familia y comunidad, Contribuye en el mejoramiento de la calidad de vida y la seguridad alimentaria de las personas mediante la formulación e implementación de proyectos de desarrollo social y programas de prevención en alimentación y nutrición de acuerdo a las problemáticas de salud de nuestro país. Diseña y gestiona proyectos con altos estándares de calidad con el objetivo de garantizar la salud y satisfacción de los pacientes mostrando un espíritu de liderazgo y ética cristiana. Lleva a cabo diferentes proyectos innovadores de investigación y desarrollo tecnológico en el marco de la nutrición, contribuyendo en el mejoramiento de la problemática alimentaria-nutricional del actual contexto de salud del país. Promueve la salud y bienestar de las personas a partir de la formulación de programas y planes de alimentación, nutricionalmente equilibrados y seguros.", campo: "Nutrición Clínica: Establecimientos de Salud de primer, de segundo y tercer nivel de atención del sistema público de salud Nutrición Comunitaria: Instituciones y organismos de gestión en salud: Ministerio de Salud, Servicios Departamental de Salud (SEDES)Nutrición y Alimentación Hotelera: Hoteles, casas de descanso de adultos mayores., restaurantes campestres, centros de esparcimiento. Gerencia de Servicios de Alimentación: servicios de alimentación de hospitales, clínicas, universidades. Docencia: universidades, institutos superiores" },
            plan_de_estudios: materiasNutricion, footer: { desc: "Te invito a ser parte de nuestra Carrera de Nutrición y Dietética que cuenta con un proyecto educativo integral, que te formará con las mejores herramientas para tener una carrera profesional plena y productiva, siempre ligada a la vocación de servicio y a una formación ética basada en valores cristianos. Nuestro compromiso es que serás parte de una carrera que te dará la posibilidad de desarrollarte con excelencia, en múltiples áreas del ámbito de la nutrición y la dietética, formándote como un profesional integral capaz de enfrentar cualquier desafío laboral, con la ayuda de Dios.", objetivos: objNutricion }
        }
    },
    {
        id: 12, head: {
            title: "Fisioterapia y Kinesiología", description: "La carrera de fisioterapia y kinesiología es una carrera líder en el mercado. Brinda una formación académica de excelencia gracias a un selecto plantel docente de gran trayectoria profesional, calidad humana y altos valores. Contamos con convenios interinstitucionales, tanto de la empresa privada como de la pública, que permite a nuestros estudiantes un óptimo desarrollo de las habilidades y destrezas que se van adquiriendo durante la formación académica, además de programas de intercambio estudiantil a diferentes países.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El perfil profesional del fisioterapeuta- kinesiólogo está orientado a la promoción, prevención, tratamiento y rehabilitación en salud, así como también de administración, educación e investigación relacionados con el cuidado de la condición fisiocinetica de las personas.", campo: "El campo laboral de los Fisioterapeutas Kinesiólogos es amplio, y contempla el trabajo en centros clínicos como hospitales, centros de salud familiar, centros ambulatorios, centros deportivos, centros especializados en el área Geriátrica, Traumatológica, Neurológica, Unidad de Terapia Intensiva, Pediátrica, geriátricos, Dermatofuncionales y empresas que se interesen en el cuidado ergonómico de sus empleados entre otros. Además, por la diversificación del campo laboral, los kinesiólogos se desempeñan en áreas de gestión, docencia e investigación." },
            plan_de_estudios: materiasFisioterapia, footer: { desc: "La carrera de Fisioterapia aborda la fundamentación teórica y práctica necesaria para comprender el movimiento corporal, su estructura y constitución. Su campo laboral esta en la prevencion, el tratameinto y la rehabilitacion de pacientes con diferentes transtornos. Si tu vocacion esta orientada a servir al projimo, eres investigador, creativo y te gusta el trabajo en equipo tu lugar esta aquí. ¡Ven que esperas para pertenecer a la familia UAB!", objetivos: objFisioterapia }
        }
    },
    {
        id: 13, head: {
            title: "Bioquímica", description: "La Bioquímica es la ciencia que estudia la base química de la vida, y como tal tiene innumerables aplicaciones en todo ámbito de la biología, y por ende, en el área de la salud humana. La carrera está programada para ocho semestres académicos (4 años). Los 3 primeros semestres están destinados a la formación básica y los siguientes a la formación especializada. La carrera culmina con el internado rotatorio, fortaleciendo los conocimientos y habilidades de los estudiantes. Durante el proceso de enseñanza el estudiante se capacita para la realización de análisis clínicos en todas sus áreas, con fines de diagnóstico, análisis de alimentos, análisis toxicológicos y otros afines a su formación, pudiendo desenvolverse en el ámbito profesional.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: " Ingreso Sin exámenes" }
        }, body: {
            perfil_campo: { perfil: "El profesional bioquímico egresado de la Universidad Adventista de Bolivia, estará capacitado para: Realizar análisis de laboratorio clínico, aplicando conocimientos y destrezas prácticas en bioquímica clínica, inmunología, hematología, microbiología y parasitología; coadyuvando con el diagnóstico de enfermedades. Ejecutar controles de calidad en laboratorio clínico. Realizar análisis de control de calidad de alimentos y agua, contribuyendo con la garantía en el expendio de los mismos.Demostrar eficiencia y eficacia en la aplicación de técnicas de laboratorio, brindando una atención de calidad al solicitante. Conformar equipos de investigación pura y aplicada dentro de las áreas de su conocimiento. Practicar un estilo de vida que demuestre el desarrollo integral de la persona y un espíritu de servicio a los demás. Impactar positivamente el entorno social mediante el mejoramiento de la calidad de vida de las personas, a través del control epidemiológico e investigación aplicada.", campo: "Laboratorio de Análisis Clínicos, tanto de Centros Hospitalarios como privados, según sus áreas. Laboratorio de Biología molecular. Laboratorio de Investigación en el área de salud Laboratorio de alimentos Laboratorio toxicológico Gestión de calidad en laboratorio clínico Otras áreas afines, relacionadas a la química, biología y biotecnología. Conformación del equipo de salud. Conformación de equipos de investigación." },
            plan_de_estudios: materiasBioquimica, footer: { desc: "Estimado estudiante: Es para mi muy grato expresarme para darte una cordial bienvenida a esta carrera, en calidad de directora de la Carrera de Bioquímica y en nombre de quienes hacen posible la formación de profesionales bioquímicos en la UAB.. Desde este ámbito del conocimiento te ofrecemos una carrera científica, cuya meta es la atención de salud a través de la atención del laboratorio. Podrás desarrollar habilidades en procedimientos especiales, con instrumentos propios del laboratorio y con una sólida base científica, que a futuro te permitirán trabajar realizando análisis clínicos en laboratorios especializados, investigación y análisis de alimentos, así como otros laboratorios relacionados al área. Por otra parte, tendrás la oportunidad de hacer prácticas en laboratorios reales e interactuar con los profesionales que se encuentran trabajando en los mismos. De esta manera, a momento de egresar contarás con una formación completa, que facilitará tu inserción laboral. La UAB te dará además una formación en valores ético-cristianos, que son muy necesarios en el trabajo profesional del bioquímico. Deseo que Dios te bendiga y con las fuerzas que Él te dará, puedas llegar a ser excelente profesional al servicio de Dios y la sociedad. Recibe un cordial saludo", objetivos: objBioquimica }
        }
    },
    {
        id: 14, head: {
            title: "Teología", description: "La carrera de Teología de la Universidad Adventista de Bolivia, tiene como objetivo formar profesionales con una sólida formación teológica, con una visión crítica y reflexiva de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad, con una formación integral, con una visión de la realidad, con una actitud de servicio y compromiso con la sociedad.",
            cardContent: { grado: "Grado Obtenido Licenciatura", modalidad: "Modalidad Presencial", duracion: "Duración 4 años (8 semestres)", ingreso: "Ingreso con examen de ingreso" }
        }, body: {
            perfil_campo: { perfil: "El profesional estará capacitado para: Proclamar el mensaje cristiano contenido en las Sagradas Escrituras a través de la evangelización personal y pública. Desempeñar funciones de pastor y administrador eclesiástico. Desempeñar funciones de capellanía y consejería en instituciones educativas, de salud y bienestar social. Redactar y editar publicaciones religiosas mediante una sólida formación académica. Realizar investigaciones en el área bíblica, teológico-histórica y pastoral, haciendo uso de los procedimientos metodológicos científicos adquiridos durante su formación académica.", campo: "Mucho campo profesioal" },
            plan_de_estudios: materiasTeologia, footer: { desc: "", objetivos: objTeologia }
        }
    },
];