export const Carreras = [
    "Ingeniería de Sistemas",
    "Ingeniería en Redes y Telecomunicaciones",
    "Ingeniería Ambiental",
    "Administración y Negocios Internacionales",
    "Contaduría Pública",
    "Ingeniería Comercial",
    "Psicología",
    "Psicopedagogía",
    "Actividad Física y Deportes",
    "Enfermería",
    "Nutrición y Dietética",
    "Fisioterapia y Kinesiología",
    "Bioquímica",
    "Teología",
]