export const materiasIngSistemas = {
    PrimerSemestre: ["Lógica", "Introducción a la Programación", "Arquitectura de Computadoras", "Física", "Fundamentos de Matemáticas",
        "Metodología del Trabajo Científico", "  Introducción General a la Biblia"],
    SegundoSemestre: ["Sistemas Digitales I", "        Estructura de Datos", "Fisica Aplicada", "Cálculo I", " Algebra Lineal", "Ingles", "Liderazgo y Comunidad"],
    TercerSemestre: ["Sistemas Digitales II", "        Contabilidad", "Programación Orientada a Objetos", "Sistemas Operativos", "Base de Datos", "Cálculo II", "Creencias Cristianas"],
    CuartoSemestre: ["Análisis y Diseño de Sistemas", "Diseño de Compiladores",
        "Taller de Programación", "Redes I",
        "Base de Datos II",
        "Estadística",
        "Vida Saludable"],
    QuintoSemestre: ["Ingeniería de Software",
        "Gerencia de Proyectos Informáticos", "Simulación y Dinámica de Sistemas", "Análisis de Algoritmos", "Redes II",
        "Taller de Base de Datos",
        "Fundamentos de la Familia y Sociedad"],
    SextoSemestre: ["Auditoria y Seguridad de Sistemas",
        "Teoría General de Sistemas",
        "Arquitectura de Software",
        "Tecnologías en Internet",
        "Investigación I",
        "Ciencia y Biblia"],
    SéptimoSemestre: ["Calidad de Software",
        "Taller de Aplicaciones en Internet",
        "Práctica Empresarial",
        "Investigación II",
        "Perspectiva Bíblica de la Historia"],
    OctavoSemestre: ["Proyecto de Grado",
        "Taller de Grado",
        "Orientación para el Desempeño",
        "Profesional"],
};